name:                learn-physics
version:             0.6.5
synopsis:            Haskell code for learning physics
description:         A library of functions for vector calculus,
                     calculation of electric field, electric flux,
                     magnetic field, and other quantities in classical mechanics,
                     electromagnetic theory, and quantum mechanics.
license:             BSD3
license-file:        LICENSE
author:              Scott N. Walck
maintainer:          Scott N. Walck <walck@lvc.edu>
category:            Physics
github:              walck/learn-physics
test-with:           GHC==9.2.4

library:
  source-dirs: src
  dependencies:
    - base
    - vector-space
    - hmatrix
    - gloss
    - gnuplot
    - not-gloss
    - spatial-math

executables:
  learn-physics-PlaneWave:
    main: examples/src/PlaneWave.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - not-gloss

  learn-physics-eFieldLine3D:
    main: examples/src/eFieldLine3D.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - not-gloss

  learn-physics-LorentzForceSimulation:
    main: examples/src/LorentzForceSimulation.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - spatial-math
      - not-gloss

  learn-physics-BCircularLoop:
    main: examples/src/BCircularLoop.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - not-gloss

  learn-physics-sunEarth:
    main: examples/src/sunEarthRK4.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - gloss

  learn-physics-eFieldLine2D:
    main: examples/src/eFieldLine2D.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - gloss

  learn-physics-Projectile:
    main: examples/src/Projectile.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - gnuplot

  learn-physics-NMR:
    main: examples/src/NMR.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics

  learn-physics-HarmonicOscillator:
    main: examples/src/HarmonicOscillator.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - gloss

  learn-physics-ElectricFluxPlot:
    main: examples/src/ElectricFluxPlot.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - gnuplot

  learn-physics-DampedOscillator:
    main: examples/src/DampedOscillator.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - learn-physics
      - gnuplot
